Add loggers to use in strategic parts
luqp/MOI pull request #72
Opened 2020-03-24 16:48 UTC by luqp

Log Level: ERROR, WARN, INFO, DEBUG, or TRACE

2020-03-24 20:08 UTC, nanrehd submitted a review, later dismissed

2020-03-25 04:15 UTC, Snip-77 requested changes
1. Please add Copyright documentation on "PythonCommandBuilder".
2. "*" is missing on the first line before the Copyright in the following classes:
-Languaje.java (Maybe change the name of this endpoint so "interaction" or something like that.
-FileService.java (delete also: <p>

2020-03-25 16:45 UTC, carlosmc23 approved these changes

2020-03-25 17:55 UTC, Snip-77 approved these changes

2020-03-25 17:56 UTC, merged